### ISSUE TITLE
There is no `extension-schemas.json` in this repo

### ISSUE THREAD

**Issue by Shihta** [jdkandersson/OpenAlchemy#41]
The example of README.md can not be executed and the error messages are shown as the follows:

```
Traceback (most recent call last):
  File "orm.py", line 1, in <module>
    from open_alchemy import init_yaml
  File "/Users/shihta/.virtualenvs/mockup2/lib/python3.7/site-packages/open_alchemy/__init__.py", line 14, in <module>
    from . import helpers as _helpers
  File "/Users/shihta/.virtualenvs/mockup2/lib/python3.7/site-packages/open_alchemy/helpers/__init__.py", line 5, in <module>
    from .get_ext_prop import get_ext_prop as get_ext_prop
  File "/Users/shihta/.virtualenvs/mockup2/lib/python3.7/site-packages/open_alchemy/helpers/get_ext_prop/__init__.py", line 13, in <module>
    with open(_SCHEMAS_FILE) as in_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shihta/.virtualenvs/mockup2/lib/python3.7/site-packages/open_alchemy/helpers/get_ext_prop/extension-schemas.json'
```

I've checked this section:

https://github.com/jdkandersson/OpenAlchemy/blob/24df38ed170cbdc98f15074783cbc8712dc89006/open_alchemy/helpers/get_ext_prop/__init__.py#L12-L14

However, there is no `extension-schemas.json` in this repo

**Comment by jdkandersson** [comment]
Thanks for the report. The problem seems to be that some static files are not being included in the distribution. I'll investigate and create a new release.

**Comment by jdkandersson** [comment]
Hi, please try on version 0.9.1 that was just released. I tested with the following files in the root directory:
- spec.yaml with the spec in the readme
- database.py:
```python
from open_alchemy import init_yaml

init_yaml("./spec.yaml")
```
- requirements.txt:
```
OpenAlchemy==0.9.1
PyYAML==5.1.2
```
- main.py:
```python
import database

from open_alchemy.models import Employee
```

Commands:
```bash
python -m venv venv
source ./venv/bin/activate
python -m pip install -r requirements.txt
python main.py
```

With 0.9.0 I reproduced the error above. With 0.9.1 the bug did not occur.

**Comment by jdkandersson** [comment]
Just for completeness, the spec.yaml file has:
```yaml
# ./examples/simple-example-spec.yml
openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate OpenAlchemy MVP.
  version: "0.1"

paths:
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          type: integer
          description: Unique identifier for the employee.
          example: 0
          x-primary-key: true
          x-autoincrement: true
        name:
          type: string
          description: The name of the employee.
          example: David Andersson
          x-index: true
        division:
          type: string
          description: The part of the company the employee works in.
          example: Engineering
          x-index: true
        salary:
          type: number
          description: The amount of money the employee is paid.
          example: 1000000.00
      required:
        - id
        - name
        - division
```

**Comment by Shihta** [comment]
Thanks! It works!
